// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: requestmedia/requestmedia.proto

package requestmedia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Overview      string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMovieRequest) Reset() {
	*x = RequestMovieRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMovieRequest) ProtoMessage() {}

func (x *RequestMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMovieRequest.ProtoReflect.Descriptor instead.
func (*RequestMovieRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMovieRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *RequestMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestMovieRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestMovieRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *RequestMovieRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type RequestMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMovieResponse) Reset() {
	*x = RequestMovieResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMovieResponse) ProtoMessage() {}

func (x *RequestMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMovieResponse.ProtoReflect.Descriptor instead.
func (*RequestMovieResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMovieResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMovieResponse) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *RequestMovieResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestTVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber  int32                  `protobuf:"varint,4,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber int32                  `protobuf:"varint,5,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Overview      string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTVRequest) Reset() {
	*x = RequestTVRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTVRequest) ProtoMessage() {}

func (x *RequestTVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTVRequest.ProtoReflect.Descriptor instead.
func (*RequestTVRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{2}
}

func (x *RequestTVRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *RequestTVRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestTVRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestTVRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *RequestTVRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *RequestTVRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

type RequestTVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SeriesId      string                 `protobuf:"bytes,2,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTVResponse) Reset() {
	*x = RequestTVResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTVResponse) ProtoMessage() {}

func (x *RequestTVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTVResponse.ProtoReflect.Descriptor instead.
func (*RequestTVResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{3}
}

func (x *RequestTVResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestTVResponse) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *RequestTVResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetStatusResponse) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *GetStatusResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetStatusResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetStatusResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_requestmedia_requestmedia_proto protoreflect.FileDescriptor

const file_requestmedia_requestmedia_proto_rawDesc = "" +
	"\n" +
	"\x1frequestmedia/requestmedia.proto\x12\x18muxcore.media.request.v1\"\x8c\x01\n" +
	"\x13RequestMovieRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\"h\n" +
	"\x14RequestMovieResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xbd\x01\n" +
	"\x10RequestTVRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12#\n" +
	"\rseason_number\x18\x04 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\x05 \x01(\x05R\repisodeNumber\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\"g\n" +
	"\x11RequestTVResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tseries_id\x18\x02 \x01(\tR\bseriesId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"1\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xe8\x01\n" +
	"\x11GetStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt2\xcb\x02\n" +
	"\x0eRequestService\x12m\n" +
	"\fRequestMovie\x12-.muxcore.media.request.v1.RequestMovieRequest\x1a..muxcore.media.request.v1.RequestMovieResponse\x12d\n" +
	"\tRequestTV\x12*.muxcore.media.request.v1.RequestTVRequest\x1a+.muxcore.media.request.v1.RequestTVResponse\x12d\n" +
	"\tGetStatus\x12*.muxcore.media.request.v1.GetStatusRequest\x1a+.muxcore.media.request.v1.GetStatusResponseBHZFgithub.com/Muxcore-Media/request-media/proto/requestmedia;requestmediab\x06proto3"

var (
	file_requestmedia_requestmedia_proto_rawDescOnce sync.Once
	file_requestmedia_requestmedia_proto_rawDescData []byte
)

func file_requestmedia_requestmedia_proto_rawDescGZIP() []byte {
	file_requestmedia_requestmedia_proto_rawDescOnce.Do(func() {
		file_requestmedia_requestmedia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_requestmedia_requestmedia_proto_rawDesc), len(file_requestmedia_requestmedia_proto_rawDesc)))
	})
	return file_requestmedia_requestmedia_proto_rawDescData
}

var file_requestmedia_requestmedia_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_requestmedia_requestmedia_proto_goTypes = []any{
	(*RequestMovieRequest)(nil),  // 0: muxcore.media.request.v1.RequestMovieRequest
	(*RequestMovieResponse)(nil), // 1: muxcore.media.request.v1.RequestMovieResponse
	(*RequestTVRequest)(nil),     // 2: muxcore.media.request.v1.RequestTVRequest
	(*RequestTVResponse)(nil),    // 3: muxcore.media.request.v1.RequestTVResponse
	(*GetStatusRequest)(nil),     // 4: muxcore.media.request.v1.GetStatusRequest
	(*GetStatusResponse)(nil),    // 5: muxcore.media.request.v1.GetStatusResponse
}
var file_requestmedia_requestmedia_proto_depIdxs = []int32{
	0, // 0: muxcore.media.request.v1.RequestService.RequestMovie:input_type -> muxcore.media.request.v1.RequestMovieRequest
	2, // 1: muxcore.media.request.v1.RequestService.RequestTV:input_type -> muxcore.media.request.v1.RequestTVRequest
	4, // 2: muxcore.media.request.v1.RequestService.GetStatus:input_type -> muxcore.media.request.v1.GetStatusRequest
	1, // 3: muxcore.media.request.v1.RequestService.RequestMovie:output_type -> muxcore.media.request.v1.RequestMovieResponse
	3, // 4: muxcore.media.request.v1.RequestService.RequestTV:output_type -> muxcore.media.request.v1.RequestTVResponse
	5, // 5: muxcore.media.request.v1.RequestService.GetStatus:output_type -> muxcore.media.request.v1.GetStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_requestmedia_requestmedia_proto_init() }
func file_requestmedia_requestmedia_proto_init() {
	if File_requestmedia_requestmedia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_requestmedia_requestmedia_proto_rawDesc), len(file_requestmedia_requestmedia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_requestmedia_requestmedia_proto_goTypes,
		DependencyIndexes: file_requestmedia_requestmedia_proto_depIdxs,
		MessageInfos:      file_requestmedia_requestmedia_proto_msgTypes,
	}.Build()
	File_requestmedia_requestmedia_proto = out.File
	file_requestmedia_requestmedia_proto_goTypes = nil
	file_requestmedia_requestmedia_proto_depIdxs = nil
}
