// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: requestmedia/requestmedia.proto

package requestmedia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMovieRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TmdbId           int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year             int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Overview         string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	Genres           []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	RequestedBy      string                 `protobuf:"bytes,6,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin          bool                   `protobuf:"varint,7,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	QualityProfileId string                 `protobuf:"bytes,8,opt,name=quality_profile_id,json=qualityProfileId,proto3" json:"quality_profile_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestMovieRequest) Reset() {
	*x = RequestMovieRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMovieRequest) ProtoMessage() {}

func (x *RequestMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMovieRequest.ProtoReflect.Descriptor instead.
func (*RequestMovieRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMovieRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *RequestMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestMovieRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestMovieRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *RequestMovieRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *RequestMovieRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestMovieRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *RequestMovieRequest) GetQualityProfileId() string {
	if x != nil {
		return x.QualityProfileId
	}
	return ""
}

type RequestMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMovieResponse) Reset() {
	*x = RequestMovieResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMovieResponse) ProtoMessage() {}

func (x *RequestMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMovieResponse.ProtoReflect.Descriptor instead.
func (*RequestMovieResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMovieResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMovieResponse) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *RequestMovieResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestTVRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TmdbId           int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year             int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber     int32                  `protobuf:"varint,4,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber    int32                  `protobuf:"varint,5,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Overview         string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	RequestedBy      string                 `protobuf:"bytes,7,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin          bool                   `protobuf:"varint,8,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	QualityProfileId string                 `protobuf:"bytes,9,opt,name=quality_profile_id,json=qualityProfileId,proto3" json:"quality_profile_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestTVRequest) Reset() {
	*x = RequestTVRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTVRequest) ProtoMessage() {}

func (x *RequestTVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTVRequest.ProtoReflect.Descriptor instead.
func (*RequestTVRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{2}
}

func (x *RequestTVRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *RequestTVRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestTVRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestTVRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *RequestTVRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *RequestTVRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *RequestTVRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestTVRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *RequestTVRequest) GetQualityProfileId() string {
	if x != nil {
		return x.QualityProfileId
	}
	return ""
}

type RequestTVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SeriesId      string                 `protobuf:"bytes,2,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTVResponse) Reset() {
	*x = RequestTVResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTVResponse) ProtoMessage() {}

func (x *RequestTVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTVResponse.ProtoReflect.Descriptor instead.
func (*RequestTVResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{3}
}

func (x *RequestTVResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestTVResponse) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *RequestTVResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestMusicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MusicbrainzId string                 `protobuf:"bytes,1,opt,name=musicbrainz_id,json=musicbrainzId,proto3" json:"musicbrainz_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Overview      string                 `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	Poster        string                 `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,5,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMusicRequest) Reset() {
	*x = RequestMusicRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMusicRequest) ProtoMessage() {}

func (x *RequestMusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMusicRequest.ProtoReflect.Descriptor instead.
func (*RequestMusicRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{4}
}

func (x *RequestMusicRequest) GetMusicbrainzId() string {
	if x != nil {
		return x.MusicbrainzId
	}
	return ""
}

func (x *RequestMusicRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestMusicRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *RequestMusicRequest) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *RequestMusicRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestMusicRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type RequestMusicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ArtistId      string                 `protobuf:"bytes,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMusicResponse) Reset() {
	*x = RequestMusicResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMusicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMusicResponse) ProtoMessage() {}

func (x *RequestMusicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMusicResponse.ProtoReflect.Descriptor instead.
func (*RequestMusicResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{5}
}

func (x *RequestMusicResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMusicResponse) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *RequestMusicResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestAlbumRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReleaseGroupId      string                 `protobuf:"bytes,1,opt,name=release_group_id,json=releaseGroupId,proto3" json:"release_group_id,omitempty"`
	ArtistMusicbrainzId string                 `protobuf:"bytes,2,opt,name=artist_musicbrainz_id,json=artistMusicbrainzId,proto3" json:"artist_musicbrainz_id,omitempty"`
	ArtistName          string                 `protobuf:"bytes,3,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Title               string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year                int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Overview            string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	RequestedBy         string                 `protobuf:"bytes,7,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin             bool                   `protobuf:"varint,8,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestAlbumRequest) Reset() {
	*x = RequestAlbumRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAlbumRequest) ProtoMessage() {}

func (x *RequestAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAlbumRequest.ProtoReflect.Descriptor instead.
func (*RequestAlbumRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{6}
}

func (x *RequestAlbumRequest) GetReleaseGroupId() string {
	if x != nil {
		return x.ReleaseGroupId
	}
	return ""
}

func (x *RequestAlbumRequest) GetArtistMusicbrainzId() string {
	if x != nil {
		return x.ArtistMusicbrainzId
	}
	return ""
}

func (x *RequestAlbumRequest) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *RequestAlbumRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestAlbumRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestAlbumRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *RequestAlbumRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestAlbumRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type RequestAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AlbumId       string                 `protobuf:"bytes,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	ArtistId      string                 `protobuf:"bytes,3,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAlbumResponse) Reset() {
	*x = RequestAlbumResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAlbumResponse) ProtoMessage() {}

func (x *RequestAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAlbumResponse.ProtoReflect.Descriptor instead.
func (*RequestAlbumResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{7}
}

func (x *RequestAlbumResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestAlbumResponse) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

func (x *RequestAlbumResponse) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *RequestAlbumResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestTrackRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RecordingId         string                 `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	ReleaseGroupId      string                 `protobuf:"bytes,2,opt,name=release_group_id,json=releaseGroupId,proto3" json:"release_group_id,omitempty"`
	ArtistMusicbrainzId string                 `protobuf:"bytes,3,opt,name=artist_musicbrainz_id,json=artistMusicbrainzId,proto3" json:"artist_musicbrainz_id,omitempty"`
	ArtistName          string                 `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Title               string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	AlbumTitle          string                 `protobuf:"bytes,6,opt,name=album_title,json=albumTitle,proto3" json:"album_title,omitempty"`
	RequestedBy         string                 `protobuf:"bytes,7,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin             bool                   `protobuf:"varint,8,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestTrackRequest) Reset() {
	*x = RequestTrackRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTrackRequest) ProtoMessage() {}

func (x *RequestTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTrackRequest.ProtoReflect.Descriptor instead.
func (*RequestTrackRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{8}
}

func (x *RequestTrackRequest) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *RequestTrackRequest) GetReleaseGroupId() string {
	if x != nil {
		return x.ReleaseGroupId
	}
	return ""
}

func (x *RequestTrackRequest) GetArtistMusicbrainzId() string {
	if x != nil {
		return x.ArtistMusicbrainzId
	}
	return ""
}

func (x *RequestTrackRequest) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *RequestTrackRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestTrackRequest) GetAlbumTitle() string {
	if x != nil {
		return x.AlbumTitle
	}
	return ""
}

func (x *RequestTrackRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestTrackRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type RequestTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AlbumId       string                 `protobuf:"bytes,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	ArtistId      string                 `protobuf:"bytes,3,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTrackResponse) Reset() {
	*x = RequestTrackResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTrackResponse) ProtoMessage() {}

func (x *RequestTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTrackResponse.ProtoReflect.Descriptor instead.
func (*RequestTrackResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{9}
}

func (x *RequestTrackResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestTrackResponse) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

func (x *RequestTrackResponse) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *RequestTrackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	AuthorName    string                 `protobuf:"bytes,2,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Isbn          string                 `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,5,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBookRequest) Reset() {
	*x = RequestBookRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBookRequest) ProtoMessage() {}

func (x *RequestBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBookRequest.ProtoReflect.Descriptor instead.
func (*RequestBookRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{10}
}

func (x *RequestBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestBookRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *RequestBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *RequestBookRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestBookRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestBookRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type RequestBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBookResponse) Reset() {
	*x = RequestBookResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBookResponse) ProtoMessage() {}

func (x *RequestBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBookResponse.ProtoReflect.Descriptor instead.
func (*RequestBookResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{11}
}

func (x *RequestBookResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestBookResponse) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *RequestBookResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *RequestBookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestComicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Publisher     string                 `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`
	ComicvineId   string                 `protobuf:"bytes,3,opt,name=comicvine_id,json=comicvineId,proto3" json:"comicvine_id,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestComicRequest) Reset() {
	*x = RequestComicRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestComicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestComicRequest) ProtoMessage() {}

func (x *RequestComicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestComicRequest.ProtoReflect.Descriptor instead.
func (*RequestComicRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{12}
}

func (x *RequestComicRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestComicRequest) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *RequestComicRequest) GetComicvineId() string {
	if x != nil {
		return x.ComicvineId
	}
	return ""
}

func (x *RequestComicRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestComicRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type RequestComicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SeriesId      string                 `protobuf:"bytes,2,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestComicResponse) Reset() {
	*x = RequestComicResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestComicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestComicResponse) ProtoMessage() {}

func (x *RequestComicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestComicResponse.ProtoReflect.Descriptor instead.
func (*RequestComicResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{13}
}

func (x *RequestComicResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestComicResponse) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *RequestComicResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestAudiobookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	AuthorName    string                 `protobuf:"bytes,2,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Narrator      string                 `protobuf:"bytes,3,opt,name=narrator,proto3" json:"narrator,omitempty"`
	Asin          string                 `protobuf:"bytes,4,opt,name=asin,proto3" json:"asin,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,6,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,7,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAudiobookRequest) Reset() {
	*x = RequestAudiobookRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAudiobookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAudiobookRequest) ProtoMessage() {}

func (x *RequestAudiobookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAudiobookRequest.ProtoReflect.Descriptor instead.
func (*RequestAudiobookRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{14}
}

func (x *RequestAudiobookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestAudiobookRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *RequestAudiobookRequest) GetNarrator() string {
	if x != nil {
		return x.Narrator
	}
	return ""
}

func (x *RequestAudiobookRequest) GetAsin() string {
	if x != nil {
		return x.Asin
	}
	return ""
}

func (x *RequestAudiobookRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestAudiobookRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestAudiobookRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type RequestAudiobookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AudiobookId   string                 `protobuf:"bytes,2,opt,name=audiobook_id,json=audiobookId,proto3" json:"audiobook_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAudiobookResponse) Reset() {
	*x = RequestAudiobookResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAudiobookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAudiobookResponse) ProtoMessage() {}

func (x *RequestAudiobookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAudiobookResponse.ProtoReflect.Descriptor instead.
func (*RequestAudiobookResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{15}
}

func (x *RequestAudiobookResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestAudiobookResponse) GetAudiobookId() string {
	if x != nil {
		return x.AudiobookId
	}
	return ""
}

func (x *RequestAudiobookResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *RequestAudiobookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,9,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,10,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt    string                 `protobuf:"bytes,11,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	StatusDetail  string                 `protobuf:"bytes,12,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"` // from automation history when in progress
	StatusLabel   string                 `protobuf:"bytes,13,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`    // human-readable label from automation history
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetStatusResponse) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *GetStatusResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetStatusResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetStatusResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetStatusResponse) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *GetStatusResponse) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *GetStatusResponse) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *GetStatusResponse) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *GetStatusResponse) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // optional filter; empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{18}
}

func (x *ListRequestsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	TmdbId        int32                  `protobuf:"varint,4,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,10,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,11,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt    string                 `protobuf:"bytes,12,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	Poster        string                 `protobuf:"bytes,13,opt,name=poster,proto3" json:"poster,omitempty"`
	StatusDetail  string                 `protobuf:"bytes,14,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"` // from automation history when in progress
	StatusLabel   string                 `protobuf:"bytes,15,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`    // human-readable label from automation history
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{19}
}

func (x *RequestInfo) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestInfo) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *RequestInfo) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RequestInfo) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *RequestInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RequestInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RequestInfo) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestInfo) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *RequestInfo) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *RequestInfo) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *RequestInfo) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *RequestInfo) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RequestInfo         `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{20}
}

func (x *ListRequestsResponse) GetRequests() []*RequestInfo {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ApproveRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequestRequest) Reset() {
	*x = ApproveRequestRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestRequest) ProtoMessage() {}

func (x *ApproveRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequestRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{21}
}

func (x *ApproveRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApproveRequestRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type ApproveRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequestResponse) Reset() {
	*x = ApproveRequestResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestResponse) ProtoMessage() {}

func (x *ApproveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestResponse.ProtoReflect.Descriptor instead.
func (*ApproveRequestResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{22}
}

func (x *ApproveRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApproveRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApproveRequestResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ApproveRequestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DenyRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeniedBy      string                 `protobuf:"bytes,2,opt,name=denied_by,json=deniedBy,proto3" json:"denied_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequestRequest) Reset() {
	*x = DenyRequestRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequestRequest) ProtoMessage() {}

func (x *DenyRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequestRequest.ProtoReflect.Descriptor instead.
func (*DenyRequestRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{23}
}

func (x *DenyRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DenyRequestRequest) GetDeniedBy() string {
	if x != nil {
		return x.DeniedBy
	}
	return ""
}

type DenyRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequestResponse) Reset() {
	*x = DenyRequestResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequestResponse) ProtoMessage() {}

func (x *DenyRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequestResponse.ProtoReflect.Descriptor instead.
func (*DenyRequestResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{24}
}

func (x *DenyRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DenyRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DenyRequestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequestRequest) Reset() {
	*x = CancelRequestRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequestRequest) ProtoMessage() {}

func (x *CancelRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequestRequest.ProtoReflect.Descriptor instead.
func (*CancelRequestRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{25}
}

func (x *CancelRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelRequestRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

type CancelRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequestResponse) Reset() {
	*x = CancelRequestResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequestResponse) ProtoMessage() {}

func (x *CancelRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequestResponse.ProtoReflect.Descriptor instead.
func (*CancelRequestResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{26}
}

func (x *CancelRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelRequestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_requestmedia_requestmedia_proto protoreflect.FileDescriptor

const file_requestmedia_requestmedia_proto_rawDesc = "" +
	"\n" +
	"\x1frequestmedia/requestmedia.proto\x12\x18muxcore.media.request.v1\"\xf8\x01\n" +
	"\x13RequestMovieRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12!\n" +
	"\frequested_by\x18\x06 \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\a \x01(\bR\aisAdmin\x12,\n" +
	"\x12quality_profile_id\x18\b \x01(\tR\x10qualityProfileId\"h\n" +
	"\x14RequestMovieResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xa9\x02\n" +
	"\x10RequestTVRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12#\n" +
	"\rseason_number\x18\x04 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\x05 \x01(\x05R\repisodeNumber\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\x12!\n" +
	"\frequested_by\x18\a \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\b \x01(\bR\aisAdmin\x12,\n" +
	"\x12quality_profile_id\x18\t \x01(\tR\x10qualityProfileId\"g\n" +
	"\x11RequestTVResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tseries_id\x18\x02 \x01(\tR\bseriesId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xc4\x01\n" +
	"\x13RequestMusicRequest\x12%\n" +
	"\x0emusicbrainz_id\x18\x01 \x01(\tR\rmusicbrainzId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\boverview\x18\x03 \x01(\tR\boverview\x12\x16\n" +
	"\x06poster\x18\x04 \x01(\tR\x06poster\x12!\n" +
	"\frequested_by\x18\x05 \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\"j\n" +
	"\x14RequestMusicResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tartist_id\x18\x02 \x01(\tR\bartistId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x98\x02\n" +
	"\x13RequestAlbumRequest\x12(\n" +
	"\x10release_group_id\x18\x01 \x01(\tR\x0ereleaseGroupId\x122\n" +
	"\x15artist_musicbrainz_id\x18\x02 \x01(\tR\x13artistMusicbrainzId\x12\x1f\n" +
	"\vartist_name\x18\x03 \x01(\tR\n" +
	"artistName\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\x12!\n" +
	"\frequested_by\x18\a \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\b \x01(\bR\aisAdmin\"\x85\x01\n" +
	"\x14RequestAlbumResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\tR\aalbumId\x12\x1b\n" +
	"\tartist_id\x18\x03 \x01(\tR\bartistId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xac\x02\n" +
	"\x13RequestTrackRequest\x12!\n" +
	"\frecording_id\x18\x01 \x01(\tR\vrecordingId\x12(\n" +
	"\x10release_group_id\x18\x02 \x01(\tR\x0ereleaseGroupId\x122\n" +
	"\x15artist_musicbrainz_id\x18\x03 \x01(\tR\x13artistMusicbrainzId\x12\x1f\n" +
	"\vartist_name\x18\x04 \x01(\tR\n" +
	"artistName\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1f\n" +
	"\valbum_title\x18\x06 \x01(\tR\n" +
	"albumTitle\x12!\n" +
	"\frequested_by\x18\a \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\b \x01(\bR\aisAdmin\"\x85\x01\n" +
	"\x14RequestTrackResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\tR\aalbumId\x12\x1b\n" +
	"\tartist_id\x18\x03 \x01(\tR\bartistId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xb1\x01\n" +
	"\x12RequestBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\vauthor_name\x18\x02 \x01(\tR\n" +
	"authorName\x12\x12\n" +
	"\x04isbn\x18\x03 \x01(\tR\x04isbn\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12!\n" +
	"\frequested_by\x18\x05 \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\"\x82\x01\n" +
	"\x13RequestBookResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xaa\x01\n" +
	"\x13RequestComicRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1c\n" +
	"\tpublisher\x18\x02 \x01(\tR\tpublisher\x12!\n" +
	"\fcomicvine_id\x18\x03 \x01(\tR\vcomicvineId\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\"j\n" +
	"\x14RequestComicResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tseries_id\x18\x02 \x01(\tR\bseriesId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xd2\x01\n" +
	"\x17RequestAudiobookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\vauthor_name\x18\x02 \x01(\tR\n" +
	"authorName\x12\x1a\n" +
	"\bnarrator\x18\x03 \x01(\tR\bnarrator\x12\x12\n" +
	"\x04asin\x18\x04 \x01(\tR\x04asin\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12!\n" +
	"\frequested_by\x18\x06 \x01(\tR\vrequestedBy\x12\x19\n" +
	"\bis_admin\x18\a \x01(\bR\aisAdmin\"\x91\x01\n" +
	"\x18RequestAudiobookResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\faudiobook_id\x18\x02 \x01(\tR\vaudiobookId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"1\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x95\x03\n" +
	"\x11GetStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12!\n" +
	"\frequested_by\x18\t \x01(\tR\vrequestedBy\x12\x1f\n" +
	"\vapproved_by\x18\n" +
	" \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\v \x01(\tR\n" +
	"approvedAt\x12#\n" +
	"\rstatus_detail\x18\f \x01(\tR\fstatusDetail\x12!\n" +
	"\fstatus_label\x18\r \x01(\tR\vstatusLabel\"-\n" +
	"\x13ListRequestsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc0\x03\n" +
	"\vRequestInfo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x17\n" +
	"\atmdb_id\x18\x04 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x06 \x01(\x05R\x04year\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12!\n" +
	"\frequested_by\x18\n" +
	" \x01(\tR\vrequestedBy\x12\x1f\n" +
	"\vapproved_by\x18\v \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\f \x01(\tR\n" +
	"approvedAt\x12\x16\n" +
	"\x06poster\x18\r \x01(\tR\x06poster\x12#\n" +
	"\rstatus_detail\x18\x0e \x01(\tR\fstatusDetail\x12!\n" +
	"\fstatus_label\x18\x0f \x01(\tR\vstatusLabel\"Y\n" +
	"\x14ListRequestsResponse\x12A\n" +
	"\brequests\x18\x01 \x03(\v2%.muxcore.media.request.v1.RequestInfoR\brequests\"W\n" +
	"\x15ApproveRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy\"~\n" +
	"\x16ApproveRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"P\n" +
	"\x12DenyRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdenied_by\x18\x02 \x01(\tR\bdeniedBy\"b\n" +
	"\x13DenyRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"X\n" +
	"\x14CancelRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fcancelled_by\x18\x02 \x01(\tR\vcancelledBy\"d\n" +
	"\x15CancelRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xb0\v\n" +
	"\x0eRequestService\x12m\n" +
	"\fRequestMovie\x12-.muxcore.media.request.v1.RequestMovieRequest\x1a..muxcore.media.request.v1.RequestMovieResponse\x12d\n" +
	"\tRequestTV\x12*.muxcore.media.request.v1.RequestTVRequest\x1a+.muxcore.media.request.v1.RequestTVResponse\x12m\n" +
	"\fRequestMusic\x12-.muxcore.media.request.v1.RequestMusicRequest\x1a..muxcore.media.request.v1.RequestMusicResponse\x12m\n" +
	"\fRequestAlbum\x12-.muxcore.media.request.v1.RequestAlbumRequest\x1a..muxcore.media.request.v1.RequestAlbumResponse\x12m\n" +
	"\fRequestTrack\x12-.muxcore.media.request.v1.RequestTrackRequest\x1a..muxcore.media.request.v1.RequestTrackResponse\x12j\n" +
	"\vRequestBook\x12,.muxcore.media.request.v1.RequestBookRequest\x1a-.muxcore.media.request.v1.RequestBookResponse\x12m\n" +
	"\fRequestComic\x12-.muxcore.media.request.v1.RequestComicRequest\x1a..muxcore.media.request.v1.RequestComicResponse\x12y\n" +
	"\x10RequestAudiobook\x121.muxcore.media.request.v1.RequestAudiobookRequest\x1a2.muxcore.media.request.v1.RequestAudiobookResponse\x12d\n" +
	"\tGetStatus\x12*.muxcore.media.request.v1.GetStatusRequest\x1a+.muxcore.media.request.v1.GetStatusResponse\x12m\n" +
	"\fListRequests\x12-.muxcore.media.request.v1.ListRequestsRequest\x1a..muxcore.media.request.v1.ListRequestsResponse\x12s\n" +
	"\x0eApproveRequest\x12/.muxcore.media.request.v1.ApproveRequestRequest\x1a0.muxcore.media.request.v1.ApproveRequestResponse\x12j\n" +
	"\vDenyRequest\x12,.muxcore.media.request.v1.DenyRequestRequest\x1a-.muxcore.media.request.v1.DenyRequestResponse\x12p\n" +
	"\rCancelRequest\x12..muxcore.media.request.v1.CancelRequestRequest\x1a/.muxcore.media.request.v1.CancelRequestResponseBHZFgithub.com/Muxcore-Media/request-media/proto/requestmedia;requestmediab\x06proto3"

var (
	file_requestmedia_requestmedia_proto_rawDescOnce sync.Once
	file_requestmedia_requestmedia_proto_rawDescData []byte
)

func file_requestmedia_requestmedia_proto_rawDescGZIP() []byte {
	file_requestmedia_requestmedia_proto_rawDescOnce.Do(func() {
		file_requestmedia_requestmedia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_requestmedia_requestmedia_proto_rawDesc), len(file_requestmedia_requestmedia_proto_rawDesc)))
	})
	return file_requestmedia_requestmedia_proto_rawDescData
}

var file_requestmedia_requestmedia_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_requestmedia_requestmedia_proto_goTypes = []any{
	(*RequestMovieRequest)(nil),      // 0: muxcore.media.request.v1.RequestMovieRequest
	(*RequestMovieResponse)(nil),     // 1: muxcore.media.request.v1.RequestMovieResponse
	(*RequestTVRequest)(nil),         // 2: muxcore.media.request.v1.RequestTVRequest
	(*RequestTVResponse)(nil),        // 3: muxcore.media.request.v1.RequestTVResponse
	(*RequestMusicRequest)(nil),      // 4: muxcore.media.request.v1.RequestMusicRequest
	(*RequestMusicResponse)(nil),     // 5: muxcore.media.request.v1.RequestMusicResponse
	(*RequestAlbumRequest)(nil),      // 6: muxcore.media.request.v1.RequestAlbumRequest
	(*RequestAlbumResponse)(nil),     // 7: muxcore.media.request.v1.RequestAlbumResponse
	(*RequestTrackRequest)(nil),      // 8: muxcore.media.request.v1.RequestTrackRequest
	(*RequestTrackResponse)(nil),     // 9: muxcore.media.request.v1.RequestTrackResponse
	(*RequestBookRequest)(nil),       // 10: muxcore.media.request.v1.RequestBookRequest
	(*RequestBookResponse)(nil),      // 11: muxcore.media.request.v1.RequestBookResponse
	(*RequestComicRequest)(nil),      // 12: muxcore.media.request.v1.RequestComicRequest
	(*RequestComicResponse)(nil),     // 13: muxcore.media.request.v1.RequestComicResponse
	(*RequestAudiobookRequest)(nil),  // 14: muxcore.media.request.v1.RequestAudiobookRequest
	(*RequestAudiobookResponse)(nil), // 15: muxcore.media.request.v1.RequestAudiobookResponse
	(*GetStatusRequest)(nil),         // 16: muxcore.media.request.v1.GetStatusRequest
	(*GetStatusResponse)(nil),        // 17: muxcore.media.request.v1.GetStatusResponse
	(*ListRequestsRequest)(nil),      // 18: muxcore.media.request.v1.ListRequestsRequest
	(*RequestInfo)(nil),              // 19: muxcore.media.request.v1.RequestInfo
	(*ListRequestsResponse)(nil),     // 20: muxcore.media.request.v1.ListRequestsResponse
	(*ApproveRequestRequest)(nil),    // 21: muxcore.media.request.v1.ApproveRequestRequest
	(*ApproveRequestResponse)(nil),   // 22: muxcore.media.request.v1.ApproveRequestResponse
	(*DenyRequestRequest)(nil),       // 23: muxcore.media.request.v1.DenyRequestRequest
	(*DenyRequestResponse)(nil),      // 24: muxcore.media.request.v1.DenyRequestResponse
	(*CancelRequestRequest)(nil),     // 25: muxcore.media.request.v1.CancelRequestRequest
	(*CancelRequestResponse)(nil),    // 26: muxcore.media.request.v1.CancelRequestResponse
}
var file_requestmedia_requestmedia_proto_depIdxs = []int32{
	19, // 0: muxcore.media.request.v1.ListRequestsResponse.requests:type_name -> muxcore.media.request.v1.RequestInfo
	0,  // 1: muxcore.media.request.v1.RequestService.RequestMovie:input_type -> muxcore.media.request.v1.RequestMovieRequest
	2,  // 2: muxcore.media.request.v1.RequestService.RequestTV:input_type -> muxcore.media.request.v1.RequestTVRequest
	4,  // 3: muxcore.media.request.v1.RequestService.RequestMusic:input_type -> muxcore.media.request.v1.RequestMusicRequest
	6,  // 4: muxcore.media.request.v1.RequestService.RequestAlbum:input_type -> muxcore.media.request.v1.RequestAlbumRequest
	8,  // 5: muxcore.media.request.v1.RequestService.RequestTrack:input_type -> muxcore.media.request.v1.RequestTrackRequest
	10, // 6: muxcore.media.request.v1.RequestService.RequestBook:input_type -> muxcore.media.request.v1.RequestBookRequest
	12, // 7: muxcore.media.request.v1.RequestService.RequestComic:input_type -> muxcore.media.request.v1.RequestComicRequest
	14, // 8: muxcore.media.request.v1.RequestService.RequestAudiobook:input_type -> muxcore.media.request.v1.RequestAudiobookRequest
	16, // 9: muxcore.media.request.v1.RequestService.GetStatus:input_type -> muxcore.media.request.v1.GetStatusRequest
	18, // 10: muxcore.media.request.v1.RequestService.ListRequests:input_type -> muxcore.media.request.v1.ListRequestsRequest
	21, // 11: muxcore.media.request.v1.RequestService.ApproveRequest:input_type -> muxcore.media.request.v1.ApproveRequestRequest
	23, // 12: muxcore.media.request.v1.RequestService.DenyRequest:input_type -> muxcore.media.request.v1.DenyRequestRequest
	25, // 13: muxcore.media.request.v1.RequestService.CancelRequest:input_type -> muxcore.media.request.v1.CancelRequestRequest
	1,  // 14: muxcore.media.request.v1.RequestService.RequestMovie:output_type -> muxcore.media.request.v1.RequestMovieResponse
	3,  // 15: muxcore.media.request.v1.RequestService.RequestTV:output_type -> muxcore.media.request.v1.RequestTVResponse
	5,  // 16: muxcore.media.request.v1.RequestService.RequestMusic:output_type -> muxcore.media.request.v1.RequestMusicResponse
	7,  // 17: muxcore.media.request.v1.RequestService.RequestAlbum:output_type -> muxcore.media.request.v1.RequestAlbumResponse
	9,  // 18: muxcore.media.request.v1.RequestService.RequestTrack:output_type -> muxcore.media.request.v1.RequestTrackResponse
	11, // 19: muxcore.media.request.v1.RequestService.RequestBook:output_type -> muxcore.media.request.v1.RequestBookResponse
	13, // 20: muxcore.media.request.v1.RequestService.RequestComic:output_type -> muxcore.media.request.v1.RequestComicResponse
	15, // 21: muxcore.media.request.v1.RequestService.RequestAudiobook:output_type -> muxcore.media.request.v1.RequestAudiobookResponse
	17, // 22: muxcore.media.request.v1.RequestService.GetStatus:output_type -> muxcore.media.request.v1.GetStatusResponse
	20, // 23: muxcore.media.request.v1.RequestService.ListRequests:output_type -> muxcore.media.request.v1.ListRequestsResponse
	22, // 24: muxcore.media.request.v1.RequestService.ApproveRequest:output_type -> muxcore.media.request.v1.ApproveRequestResponse
	24, // 25: muxcore.media.request.v1.RequestService.DenyRequest:output_type -> muxcore.media.request.v1.DenyRequestResponse
	26, // 26: muxcore.media.request.v1.RequestService.CancelRequest:output_type -> muxcore.media.request.v1.CancelRequestResponse
	14, // [14:27] is the sub-list for method output_type
	1,  // [1:14] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_requestmedia_requestmedia_proto_init() }
func file_requestmedia_requestmedia_proto_init() {
	if File_requestmedia_requestmedia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_requestmedia_requestmedia_proto_rawDesc), len(file_requestmedia_requestmedia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_requestmedia_requestmedia_proto_goTypes,
		DependencyIndexes: file_requestmedia_requestmedia_proto_depIdxs,
		MessageInfos:      file_requestmedia_requestmedia_proto_msgTypes,
	}.Build()
	File_requestmedia_requestmedia_proto = out.File
	file_requestmedia_requestmedia_proto_goTypes = nil
	file_requestmedia_requestmedia_proto_depIdxs = nil
}
