// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: requestmedia/requestmedia.proto

package requestmedia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Overview      string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMovieRequest) Reset() {
	*x = RequestMovieRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMovieRequest) ProtoMessage() {}

func (x *RequestMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMovieRequest.ProtoReflect.Descriptor instead.
func (*RequestMovieRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMovieRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *RequestMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestMovieRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestMovieRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *RequestMovieRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type RequestMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMovieResponse) Reset() {
	*x = RequestMovieResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMovieResponse) ProtoMessage() {}

func (x *RequestMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMovieResponse.ProtoReflect.Descriptor instead.
func (*RequestMovieResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMovieResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMovieResponse) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *RequestMovieResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestTVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber  int32                  `protobuf:"varint,4,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber int32                  `protobuf:"varint,5,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Overview      string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTVRequest) Reset() {
	*x = RequestTVRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTVRequest) ProtoMessage() {}

func (x *RequestTVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTVRequest.ProtoReflect.Descriptor instead.
func (*RequestTVRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{2}
}

func (x *RequestTVRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *RequestTVRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestTVRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestTVRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *RequestTVRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *RequestTVRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

type RequestTVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SeriesId      string                 `protobuf:"bytes,2,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTVResponse) Reset() {
	*x = RequestTVResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTVResponse) ProtoMessage() {}

func (x *RequestTVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTVResponse.ProtoReflect.Descriptor instead.
func (*RequestTVResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{3}
}

func (x *RequestTVResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestTVResponse) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *RequestTVResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DenyReason    string                 `protobuf:"bytes,9,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,10,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetStatusResponse) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *GetStatusResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetStatusResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetStatusResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetStatusResponse) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

func (x *GetStatusResponse) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type ListRequestsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty status returns all requests. Common values: pending, denied, watchlisted.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestedBy   string `protobuf:"bytes,2,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequestsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRequestsRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type RequestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DenyReason    string                 `protobuf:"bytes,9,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,10,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	TmdbId        int32                  `protobuf:"varint,11,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEntry) Reset() {
	*x = RequestEntry{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEntry) ProtoMessage() {}

func (x *RequestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEntry.ProtoReflect.Descriptor instead.
func (*RequestEntry) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{7}
}

func (x *RequestEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestEntry) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *RequestEntry) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RequestEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestEntry) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RequestEntry) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RequestEntry) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

func (x *RequestEntry) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *RequestEntry) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RequestEntry        `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequestsResponse) GetRequests() []*RequestEntry {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ApproveRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequestRequest) Reset() {
	*x = ApproveRequestRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestRequest) ProtoMessage() {}

func (x *ApproveRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequestRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{9}
}

func (x *ApproveRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApproveRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequestResponse) Reset() {
	*x = ApproveRequestResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestResponse) ProtoMessage() {}

func (x *ApproveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestResponse.ProtoReflect.Descriptor instead.
func (*ApproveRequestResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{10}
}

func (x *ApproveRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApproveRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApproveRequestResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type DenyRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequestRequest) Reset() {
	*x = DenyRequestRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequestRequest) ProtoMessage() {}

func (x *DenyRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequestRequest.ProtoReflect.Descriptor instead.
func (*DenyRequestRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{11}
}

func (x *DenyRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DenyRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DenyRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DenyReason    string                 `protobuf:"bytes,3,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequestResponse) Reset() {
	*x = DenyRequestResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequestResponse) ProtoMessage() {}

func (x *DenyRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequestResponse.ProtoReflect.Descriptor instead.
func (*DenyRequestResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{12}
}

func (x *DenyRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DenyRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DenyRequestResponse) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

type AddToWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	TmdbId        int32                  `protobuf:"varint,2,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Poster        string                 `protobuf:"bytes,5,opt,name=poster,proto3" json:"poster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToWatchlistRequest) Reset() {
	*x = AddToWatchlistRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWatchlistRequest) ProtoMessage() {}

func (x *AddToWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWatchlistRequest.ProtoReflect.Descriptor instead.
func (*AddToWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{13}
}

func (x *AddToWatchlistRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *AddToWatchlistRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *AddToWatchlistRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddToWatchlistRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddToWatchlistRequest) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

type AddToWatchlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToWatchlistResponse) Reset() {
	*x = AddToWatchlistResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWatchlistResponse) ProtoMessage() {}

func (x *AddToWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWatchlistResponse.ProtoReflect.Descriptor instead.
func (*AddToWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{14}
}

func (x *AddToWatchlistResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AddToWatchlistResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveFromWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromWatchlistRequest) Reset() {
	*x = RemoveFromWatchlistRequest{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWatchlistRequest) ProtoMessage() {}

func (x *RemoveFromWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWatchlistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveFromWatchlistRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RemoveFromWatchlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromWatchlistResponse) Reset() {
	*x = RemoveFromWatchlistResponse{}
	mi := &file_requestmedia_requestmedia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWatchlistResponse) ProtoMessage() {}

func (x *RemoveFromWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requestmedia_requestmedia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWatchlistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_requestmedia_requestmedia_proto_rawDescGZIP(), []int{16}
}

var File_requestmedia_requestmedia_proto protoreflect.FileDescriptor

const file_requestmedia_requestmedia_proto_rawDesc = "" +
	"\n" +
	"\x1frequestmedia/requestmedia.proto\x12\x18muxcore.media.request.v1\"\x8c\x01\n" +
	"\x13RequestMovieRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\"h\n" +
	"\x14RequestMovieResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xbd\x01\n" +
	"\x10RequestTVRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12#\n" +
	"\rseason_number\x18\x04 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\x05 \x01(\x05R\repisodeNumber\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\"g\n" +
	"\x11RequestTVResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tseries_id\x18\x02 \x01(\tR\bseriesId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"1\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xac\x02\n" +
	"\x11GetStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vdeny_reason\x18\t \x01(\tR\n" +
	"denyReason\x12!\n" +
	"\frequested_by\x18\n" +
	" \x01(\tR\vrequestedBy\"P\n" +
	"\x13ListRequestsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\frequested_by\x18\x02 \x01(\tR\vrequestedBy\"\xc0\x02\n" +
	"\fRequestEntry\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vdeny_reason\x18\t \x01(\tR\n" +
	"denyReason\x12!\n" +
	"\frequested_by\x18\n" +
	" \x01(\tR\vrequestedBy\x12\x17\n" +
	"\atmdb_id\x18\v \x01(\x05R\x06tmdbId\"Z\n" +
	"\x14ListRequestsResponse\x12B\n" +
	"\brequests\x18\x01 \x03(\v2&.muxcore.media.request.v1.RequestEntryR\brequests\"6\n" +
	"\x15ApproveRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"h\n" +
	"\x16ApproveRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\"K\n" +
	"\x12DenyRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"m\n" +
	"\x13DenyRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vdeny_reason\x18\x03 \x01(\tR\n" +
	"denyReason\"\x8f\x01\n" +
	"\x15AddToWatchlistRequest\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12\x17\n" +
	"\atmdb_id\x18\x02 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x16\n" +
	"\x06poster\x18\x05 \x01(\tR\x06poster\"O\n" +
	"\x16AddToWatchlistResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\";\n" +
	"\x1aRemoveFromWatchlistRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x1d\n" +
	"\x1bRemoveFromWatchlistResponse2\x95\a\n" +
	"\x0eRequestService\x12m\n" +
	"\fRequestMovie\x12-.muxcore.media.request.v1.RequestMovieRequest\x1a..muxcore.media.request.v1.RequestMovieResponse\x12d\n" +
	"\tRequestTV\x12*.muxcore.media.request.v1.RequestTVRequest\x1a+.muxcore.media.request.v1.RequestTVResponse\x12d\n" +
	"\tGetStatus\x12*.muxcore.media.request.v1.GetStatusRequest\x1a+.muxcore.media.request.v1.GetStatusResponse\x12m\n" +
	"\fListRequests\x12-.muxcore.media.request.v1.ListRequestsRequest\x1a..muxcore.media.request.v1.ListRequestsResponse\x12s\n" +
	"\x0eApproveRequest\x12/.muxcore.media.request.v1.ApproveRequestRequest\x1a0.muxcore.media.request.v1.ApproveRequestResponse\x12j\n" +
	"\vDenyRequest\x12,.muxcore.media.request.v1.DenyRequestRequest\x1a-.muxcore.media.request.v1.DenyRequestResponse\x12s\n" +
	"\x0eAddToWatchlist\x12/.muxcore.media.request.v1.AddToWatchlistRequest\x1a0.muxcore.media.request.v1.AddToWatchlistResponse\x12\x82\x01\n" +
	"\x13RemoveFromWatchlist\x124.muxcore.media.request.v1.RemoveFromWatchlistRequest\x1a5.muxcore.media.request.v1.RemoveFromWatchlistResponseBHZFgithub.com/Muxcore-Media/request-media/proto/requestmedia;requestmediab\x06proto3"

var (
	file_requestmedia_requestmedia_proto_rawDescOnce sync.Once
	file_requestmedia_requestmedia_proto_rawDescData []byte
)

func file_requestmedia_requestmedia_proto_rawDescGZIP() []byte {
	file_requestmedia_requestmedia_proto_rawDescOnce.Do(func() {
		file_requestmedia_requestmedia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_requestmedia_requestmedia_proto_rawDesc), len(file_requestmedia_requestmedia_proto_rawDesc)))
	})
	return file_requestmedia_requestmedia_proto_rawDescData
}

var file_requestmedia_requestmedia_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_requestmedia_requestmedia_proto_goTypes = []any{
	(*RequestMovieRequest)(nil),         // 0: muxcore.media.request.v1.RequestMovieRequest
	(*RequestMovieResponse)(nil),        // 1: muxcore.media.request.v1.RequestMovieResponse
	(*RequestTVRequest)(nil),            // 2: muxcore.media.request.v1.RequestTVRequest
	(*RequestTVResponse)(nil),           // 3: muxcore.media.request.v1.RequestTVResponse
	(*GetStatusRequest)(nil),            // 4: muxcore.media.request.v1.GetStatusRequest
	(*GetStatusResponse)(nil),           // 5: muxcore.media.request.v1.GetStatusResponse
	(*ListRequestsRequest)(nil),         // 6: muxcore.media.request.v1.ListRequestsRequest
	(*RequestEntry)(nil),                // 7: muxcore.media.request.v1.RequestEntry
	(*ListRequestsResponse)(nil),        // 8: muxcore.media.request.v1.ListRequestsResponse
	(*ApproveRequestRequest)(nil),       // 9: muxcore.media.request.v1.ApproveRequestRequest
	(*ApproveRequestResponse)(nil),      // 10: muxcore.media.request.v1.ApproveRequestResponse
	(*DenyRequestRequest)(nil),          // 11: muxcore.media.request.v1.DenyRequestRequest
	(*DenyRequestResponse)(nil),         // 12: muxcore.media.request.v1.DenyRequestResponse
	(*AddToWatchlistRequest)(nil),       // 13: muxcore.media.request.v1.AddToWatchlistRequest
	(*AddToWatchlistResponse)(nil),      // 14: muxcore.media.request.v1.AddToWatchlistResponse
	(*RemoveFromWatchlistRequest)(nil),  // 15: muxcore.media.request.v1.RemoveFromWatchlistRequest
	(*RemoveFromWatchlistResponse)(nil), // 16: muxcore.media.request.v1.RemoveFromWatchlistResponse
}
var file_requestmedia_requestmedia_proto_depIdxs = []int32{
	7,  // 0: muxcore.media.request.v1.ListRequestsResponse.requests:type_name -> muxcore.media.request.v1.RequestEntry
	0,  // 1: muxcore.media.request.v1.RequestService.RequestMovie:input_type -> muxcore.media.request.v1.RequestMovieRequest
	2,  // 2: muxcore.media.request.v1.RequestService.RequestTV:input_type -> muxcore.media.request.v1.RequestTVRequest
	4,  // 3: muxcore.media.request.v1.RequestService.GetStatus:input_type -> muxcore.media.request.v1.GetStatusRequest
	6,  // 4: muxcore.media.request.v1.RequestService.ListRequests:input_type -> muxcore.media.request.v1.ListRequestsRequest
	9,  // 5: muxcore.media.request.v1.RequestService.ApproveRequest:input_type -> muxcore.media.request.v1.ApproveRequestRequest
	11, // 6: muxcore.media.request.v1.RequestService.DenyRequest:input_type -> muxcore.media.request.v1.DenyRequestRequest
	13, // 7: muxcore.media.request.v1.RequestService.AddToWatchlist:input_type -> muxcore.media.request.v1.AddToWatchlistRequest
	15, // 8: muxcore.media.request.v1.RequestService.RemoveFromWatchlist:input_type -> muxcore.media.request.v1.RemoveFromWatchlistRequest
	1,  // 9: muxcore.media.request.v1.RequestService.RequestMovie:output_type -> muxcore.media.request.v1.RequestMovieResponse
	3,  // 10: muxcore.media.request.v1.RequestService.RequestTV:output_type -> muxcore.media.request.v1.RequestTVResponse
	5,  // 11: muxcore.media.request.v1.RequestService.GetStatus:output_type -> muxcore.media.request.v1.GetStatusResponse
	8,  // 12: muxcore.media.request.v1.RequestService.ListRequests:output_type -> muxcore.media.request.v1.ListRequestsResponse
	10, // 13: muxcore.media.request.v1.RequestService.ApproveRequest:output_type -> muxcore.media.request.v1.ApproveRequestResponse
	12, // 14: muxcore.media.request.v1.RequestService.DenyRequest:output_type -> muxcore.media.request.v1.DenyRequestResponse
	14, // 15: muxcore.media.request.v1.RequestService.AddToWatchlist:output_type -> muxcore.media.request.v1.AddToWatchlistResponse
	16, // 16: muxcore.media.request.v1.RequestService.RemoveFromWatchlist:output_type -> muxcore.media.request.v1.RemoveFromWatchlistResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_requestmedia_requestmedia_proto_init() }
func file_requestmedia_requestmedia_proto_init() {
	if File_requestmedia_requestmedia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_requestmedia_requestmedia_proto_rawDesc), len(file_requestmedia_requestmedia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_requestmedia_requestmedia_proto_goTypes,
		DependencyIndexes: file_requestmedia_requestmedia_proto_depIdxs,
		MessageInfos:      file_requestmedia_requestmedia_proto_msgTypes,
	}.Build()
	File_requestmedia_requestmedia_proto = out.File
	file_requestmedia_requestmedia_proto_goTypes = nil
	file_requestmedia_requestmedia_proto_depIdxs = nil
}
